id: I156B76B6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:35:46+00:00'
last_modified: '2022-06-07T15:26:00.946754+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00PD1011326
  title: བྱམས་པ་འཕྲིན་ལས་མཆོག་གི་བོད་ལུགས་གསོ་རིག་གི་དྲན་གསོས་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    FB59:
      image_group_id: I2KG209836
      title: ''
      total_pages: 224
      order: 1
      base_file: FB59.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
